from enum import StrEnum

__all__ = ("Equipment", "Ghosts")


class Equipment(StrEnum):
    crucifix = "Crucifix"
    dots_projector = "DOTSProjector"
    emf_reader = "EMFReader"
    firelight = "Firelight"
    flashlight = "Flashlight"
    ghost_writing_book = "GhostWritingBook"
    headgear = "HeadGear"
    igniter = "Igniter"
    motion_sensor = "MotionSensor"
    parabolic_microphone = "ParabolicMicrophone"
    photo_camera = "PhotoCamera"
    repellent = "Repellent"
    incense = "Repellent"
    salt = "Salt"
    sanity_medication = "SanityMedication"
    sound_recorder = "SoundRecorder"
    sound_sensor = "SoundSensor"
    spirit_box = "SpiritBox"
    thermometer = "Thermometer"
    tripod = "Tripod"
    uv_light = "UVLight"
    video_camera = "VideoCamera"


class Ghosts(StrEnum):
    banshee = "Banshee"
    demon = "Demon"
    deogen = "Deogen"
    goryo = "Goryo"
    hantu = "Hantu"
    jinn = "Jinn"
    mare = "Mare"
    mimic = "Mimic"
    moroi = "Moroi"
    myling = "Myling"
    obake = "Obake"
    oni = "Oni"
    onryo = "Onryo"
    phantom = "Phantom"
    poltergeist = "Poltergeist"
    raiju = "Raiju"
    revenant = "Revenant"
    shade = "Shade"
    spirit = "Spirit"
    thaye = "Thaye"
    the_twins = "TheTwins"
    wraith = "Wraith"
    yokai = "Yokai"
    yurei = "Yurei"
