?start: value

?value: object
      | array
      | ESCAPED_STRING     -> string
      | SIGNED_NUMBER      -> number
      | "true"             -> true
      | "false"            -> false
      | "null"             -> null

array : "[" [value ("," value)*] "]"

object : "{" [object_item ("," object_item)*] "}"

?object_item : member
             | dict_entry

member : es3_key ":" value

?es3_key: SIGNED_NUMBER -> numeric_key
        | ESCAPED_STRING -> string_key

dict_entry : object ":" value

%import common.ESCAPED_STRING
%import common.SIGNED_NUMBER
%import common.WS

%ignore WS
